server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13341/boarddb
    username: root
    password: root
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true
    p6spy:
      # JDBC ??? ??? ?? P6LogFactory ??
      enable-logging: true
      # com.p6spy.engine.spy.appender.MultiLineFormat ?? (SingleLineFormat ??)
      multiline: true
      # ?? ????? ?? ?? ?? [slf4j, sysout, file, custom]
      logging: slf4j
      # ?? ??? '?'? ??? ???? SQL ???? ?? ???? ??
      # ??: ? ??? ?? ???? ??? ?? ??
      tracing:
        include-parameter-values: true
  # JPA ??
  jpa:
    database : mysql
    hibernate:
      ddl-auto: none
      # ddl-auto: create-drop
    properties:
      hibernate:
        jdbc.batch_size: 1000
        format_sql: true
        # show_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
    open-in-view: false

  http:
    media-type:
      default-charset: UTF-8
      default-content-type: application/json

# cors ??
cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# ?? ?? secret Key ? RedirectUri ??
#token:
#  auth:
#    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
#    accessTokenExpiry: 1800000
#    refreshTokenExpiry: 604800000
#    accessTokenHeaderName: "Authorization"
#    accessTokenHeaderPrefix: "Bearer "
#    refreshTokenName: "refresh_token"
#  oauth2:
#    authorizedRedirectUris:
#      - http://localhost:3000/oauth/redirect

logging:
  level:
    root: info
    #org:
     # hibernate: info